displayName: Keycloak Oauth2 introspection

type: middleware

import: github.com/augusto-sb/traefik-plugin-keycloak-oauth2-introspection

testData:
  KeycloakIntrospectionEndpoint: "https://auth.example.com/realms/myrealm/protocol/openid-connect/token/introspect"
  ClientID: "my-private-client"
  ClientSecret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

summary: 'traefik plugin to validate jwt tokens against keycloak and verify if active'